[project]
authors = ["Marlon Menendez <44656927+mmenendezg@users.noreply.github.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "algos"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
max = ">=24.6.0,<25"

[pypi-dependencies]
ipykernel = ">=6.29.5, <7"
ruff = ">=0.8.3, <0.9"
icecream = ">=2.1.3, <3"
ipywidgets = ">=8.1.5, <9"
pygame = ">=2.6.1, <3"

[tasks]
life = "mojo learning-mojo/life.🔥"
